### ISSUE TITLE
Varanny appears blocked in Windows

### ISSUE THREAD

**Issue by JojoKN6HTD** [islandmagic/varanny#17]
Hi Georges, I installed Varanny in two different Windows machines (Windows 10), and a window starts but does not open at all. What could be the issue? I have VARA FM running in the background. I already tried to modify the Windows security settings to allow the most freedom in launching programs from any source. Any solution to this Varanny .exe not starting? Thanks.

**Comment by georges** [comment]
What do you see when you start `varanny` from a terminal window?
