### ISSUE TITLE
Varrany stops working in Windows 11

### ISSUE THREAD

**Issue by guilfu134** [islandmagic/varanny#18]
I am trying to get my Varanny / Radiomail setup working.
I am having issues with Varanny starting then I connect with Radiomail than Varanny disconnects with a an error message:
 [WASAPI] Data Discontinuity (possible overrun). Attempting recovery.
2024/10/26 21:32:51 Client closed the connection
2024/10/26 21:32:51 Cleaning up after closing connection
Stopping monitoring...
Then the black command screen just stays open.
I am running Varrany in a Lenovo Thinkcentre M700 with Windows 11 installed. I have followed the instructions the best that I can.
Vara has been installed on this PC as well as Winlink Express and they both work with no issues. I also installed MyPublicWIFI and set it up per your instructions. I can connect to PC with my IPhone. I am using a digirig and a DRA30 as sound cards and both have been tested and working properly with Winlink. I also purchased the display port emulator plugs (this pc has display ports instead of HDMI) for use as a headless computer when it finally works.
I edited the json file as suggested in the instructions. Had some problems editing but it finally worked.
I am a radio technician and an experienced ham repairing and putting together hardware and antennas but I am not an IT professional. I know my way around computers through experience (that is how I've gotten this far) but I am not an expert.
Any suggestions on getting my setup working will be greatly appreciated.

**Comment by guilfu134** [comment]
![IMG_9190](https://github.com/user-attachments/assets/a834c253-bb02-4a99-a206-e4cc04b24bc8)
![IMG_9185](https://github.com/user-attachments/assets/8fbc95ff-43cb-4e88-bcf9-858195bccc0c)
Screen shot of json file and of my failed “build from source”.

**Comment by georges** [comment]
Looks like you're running into a problem when using the audio monitor from RadioMail? From what I can tell, seems that varanny is running into an exception when trying to connect to the sound card.

I have not tested Windows 11 so, not sure if this is a problem with that or perhaps that particular sound card.

This functionality is not required to get VARA to work. Have you tried to establish a connection in RadioMail? It should launch VARA for you.

**Comment by guilfu134** [comment]
Thank you very much for your reply.
When I try to connect, once I choose which radio to use, the connection is
established and For the short period it is working (only a few seconds) I
can check the audio monitor and it is working. Shortly after that the
connection is lost. The program does not give me time to send an email.
What should I try now?

Felipe Guilfuchi Ramos
WP4DMD

**Comment by georges** [comment]
Don't go into the Audio Input Monitor in RadioMail. Just select the radio and go back to the main screen. From there, try to connect to a station.

**Comment by guilfu134** [comment]
Thanks for the information. I will try it this evening and let you know how
it works. I will also test it out with the DRA30 souncard and let you know
how it goes.

**Comment by guilfu134** [comment]
![IMG_9195](https://github.com/user-attachments/assets/ba374e2f-0639-4c76-a4ca-22d096b27a64)

**Comment by guilfu134** [comment]
Tested with DRA30 sound card and same issues. Ran Varanni without checking audio monitor. It did not generate overrun. I tried to reconnect to do more tests but could not find my modems / radios. I had to reset pc for more tests. My public wifi won’t let me reset pc until I change wifi connection on my iphone.

**Comment by guilfu134** [comment]
![Uploading IMG_9197.png…]()

**Comment by guilfu134** [comment]
I finally made a connection and sent an email. Yes, the problem is with the audio monitor. I will do more tests with the DRA30 sound card and my base radio. I will post the results. I am still getting used to using Radiomail and Varanni. I am more familiar with Winlink.

**Comment by guilfu134** [comment]
![Uploading IMG_9198.jpeg…]()

**Comment by guilfu134** [comment]
Connection made with DRA30. Both souncards work. I did not touch the Audio Monitor.

**Comment by guilfu134** [comment]
Had problems uploading images from my iphone. will try later.

**Comment by guilfu134** [comment]
![IMG_9198](https://github.com/user-attachments/assets/fdac5dff-a302-4747-8812-719b5d87fcfe)

**Comment by guilfu134** [comment]
Image of Varanni connecting with DRA30 soundcard which did not upload yesterday.

**Comment by guilfu134** [comment]
![IMG_9197](https://github.com/user-attachments/assets/5434209d-73d5-4cca-9abf-c2bbb222dc70)

**Comment by guilfu134** [comment]
Image of succesful connection which did not uplod yesterday.

**Comment by georges** [comment]
Great to hear you got it working.

**Comment by guilfu134** [comment]
I am still running tests. It is working despite the error message. I have
been testing with both soud cards and have been using the audio monitor on
purpose and have been able to reconnect and send emails. I still have to
setup Varanni to run at startup. I downloaded a tutorial on setting this
up. I will post some more screen shots so you can study them.

**Comment by guilfu134** [comment]
![IMG_9200](https://github.com/user-attachments/assets/789fcf13-80d4-428a-8339-2b133fc0df9b)
![IMG_9202](https://github.com/user-attachments/assets/74200a02-feb1-47fc-b1f8-b82ff8a4b231)
![IMG_9203](https://github.com/user-attachments/assets/5b58b039-b194-4ca0-aa5a-0412b746fb5c)
![IMG_9205](https://github.com/user-attachments/assets/ca3fc09d-14c6-4407-9570-c8badfaa6a28)
![IMG_9206](https://github.com/user-attachments/assets/afc95ee1-6239-4a80-86fc-3f02462ee214)

**Comment by guilfu134** [comment]
Varrani is working despite error message. Tested with both soundcards, digirig and dra30.

**Comment by guilfu134** [comment]
Oh,…and the audio monotor IS working!

**Comment by georges** [comment]
So, everything is working then?

**Comment by guilfu134** [comment]
I closed the issue by accident and then reopened it.
Things look like they are working. Should the error message be ignored?
Will there be an update? Are there any other suggestions to make the
instalation and configuring of Varanni a bit more troublefree for us none
coders?

**Comment by georges** [comment]
Yeah the messages are mostly from other libraries so nothing to worry about.

**Comment by guilfu134** [comment]
![IMG_9208](https://github.com/user-attachments/assets/055b7213-9f1f-406b-ba87-f5c846f02d43)
![IMG_9207](https://github.com/user-attachments/assets/a3576f4f-e6a3-4f34-b9e0-9bea38c4ff42)

**Comment by georges** [comment]
VARA stores your license key in the .ini file. If you have created specific .ini files for a configuration that varanny uses, make sure that .ini file has the key in it too.

**Comment by guilfu134** [comment]
![IMG_9209](https://github.com/user-attachments/assets/af0a5f1c-b67d-479b-8d42-259801b682f8)

**Comment by guilfu134** [comment]
I just received your reply. How is the Vara .ini file edited to add this information?
I also have an issue with My Public Wifi. When computer boots up, after My Public Wifi starts, the setup screen opens up and there information page opens up in the background. I can shut down the information page but not the setup screen. This happens intermitantly.

**Comment by guilfu134** [comment]
![IMG_9210](https://github.com/user-attachments/assets/2bfcbfbf-2adb-40f5-a855-ffd093f2ca82)

**Comment by guilfu134** [comment]
Original Vara .ini file

**Comment by guilfu134** [comment]
![image](https://github.com/user-attachments/assets/ca94b8c6-cfd7-48b0-ad06-68ad95ecffa8)

**Comment by guilfu134** [comment]
Varafm.digirig.ini file

**Comment by guilfu134** [comment]
![image](https://github.com/user-attachments/assets/6a410693-3bfd-422a-aa4e-9177ef9de5dd)

**Comment by guilfu134** [comment]
Varafn.dra30.ini file

**Comment by guilfu134** [comment]
Varafm.dra30.ini

**Comment by georges** [comment]
I deleted your screen shot because I don't think it's a good idea to post your license information on public boards. You can edit .ini file with a text editor. I'm afraid I can't spend more time troubleshooting your installation.

**Comment by guilfu134** [comment]
I am sorry for posting license information. Did it unintentionaly. Just one last comment / question before closing this issue. All three .ini files had the license and activation code. Is there smething else I should verify to correct this problem?
