### ISSUE TITLE
Delay= parameter not found in varrani.json file.

### ISSUE THREAD

**Issue by guilfu134** [islandmagic/varanny#19]
I had to substitute MyPublicWifi for Connectify to get my setup working. Connectify takes a bit longer to initialize and I'm having the issue you mention in your troubleshooting instructions.
My varanni.json file does not have this parameter nor do the examples in your instructions.
Where does it go?
By the way, I switched to Connectify because MyPublicWifi did not let my PC shutdown intermittently. I had to force it to shutdown with the long press of the power button risking data loss or hard disk corruption. Connectify works properly.

**Comment by georges** [comment]
You would add it as a top parameter, such as:

```
{
 "Port": 8273,
  "Delay": 15,
  "Modems" : [
```

**Comment by guilfu134** [comment]
Thanks!
