### ISSUE TITLE
Varanny won't install on Windows 11

### ISSUE THREAD

**Issue by kx8u** [islandmagic/varanny#2]
Tried to install on my Windows 11 laptop, build 22631.2715 version 23H2. I downloaded and unzipped the installer then. clicked on varanna.exe to install. I could see a flash as if a window started to open then in immediately closed. 

David
KX8U

**Comment by kx8u** [comment]
Additionally I get a multiple undefined errors when I try to build from source. I have never used GO so I may be doing it wrong.

**Comment by georges** [comment]
There is no installer. `varanny.exe` is a command line executable. You need to unzip in a folder and then start from the command line.
