### ISSUE TITLE
This is what I have found so far

### ISSUE THREAD

**Issue by ae4ml** [islandmagic/varanny#3]
I was successful on getting varaFM working however not so lucky with varaHF. 
I run Ubuntu and Windows 10 Pro here. 

This also comes down to a mDNS issue. There is no ip or mac address resolution that I can detect. 
admiral@DS9:~$ telnet MyVaraFM 8273
Server lookup failure:  MyVaraFM:8273, Name or service not known

admiral@DS9:~$ avahi-browse -a
+   eno1 IPv4 MyVaraFM                                      _varafm-modem._tcp   local
+   eno1 IPv4 MyVaraHF                                      _varahf-modem._tcp   local
+   eno1 IPv4 24FD5B000001AB64                              _smartthings._tcp    local
+   eno1 IPv4 amzn.dmgr:C336C428451D83CB3AA4E7E0F294BC31:IWtzu2uork:480560 Amazon Fire TV       local

 I can see both of my entries being broadcast and I can validate this on several devices. 
1. I can't telnet via .local name to port 8273 but using an ip address it works. 
2. my entries MyVaraFM is first entry and it works on my iphone and I have send several messages
3. MyVaraHF only gets a Connection timed out. when it looks for a connection 

if I telnet via ip I can get both fm and hf to work.

**Comment by georges** [comment]
I believe you're missing one step here. The `MyVaraFM` is a human readable name descriptor that's being used to broadcast your modem. It's different from the hostname that your computer is using.

This lists the services advertised:

```
$ avahi-browse -v _varafm-modem._tcp
Server version: avahi 0.8; Host name: t4.local
E Ifce Prot Name                                          Type                 Domain
+ wlp2s0 IPv6 IC705FM                                       _varafm-modem._tcp   local
+ wlp2s0 IPv6 THD74FM                                       _varafm-modem._tcp   local
+ wlp2s0 IPv4 THD74FM                                       _varafm-modem._tcp   local
+ wlp2s0 IPv4 IC705FM                                       _varafm-modem._tcp   local
: Cache exhausted
: All for now

```

Then, to resolve each service, you can use:

```
$ avahi-browse -r _varafm-modem._tcp
+ wlp2s0 IPv6 IC705FM                                       _varafm-modem._tcp   local
+ wlp2s0 IPv6 THD74FM                                       _varafm-modem._tcp   local
+ wlp2s0 IPv4 THD74FM                                       _varafm-modem._tcp   local
+ wlp2s0 IPv4 IC705FM                                       _varafm-modem._tcp   local
= wlp2s0 IPv6 IC705FM                                       _varafm-modem._tcp   local
   hostname = [t4windoz.local]
   address = [192.168.137.1]
   port = [8300]
   txt = ["launchport=8273;"]
= wlp2s0 IPv6 THD74FM                                       _varafm-modem._tcp   local
   hostname = [t4windoz.local]
   address = [192.168.137.1]
   port = [8300]
   txt = ["launchport=8273;"]
= wlp2s0 IPv4 THD74FM                                       _varafm-modem._tcp   local
   hostname = [t4windoz.local]
   address = [192.168.137.1]
   port = [8300]
   txt = ["launchport=8273;"]
= wlp2s0 IPv4 IC705FM                                       _varafm-modem._tcp   local
   hostname = [t4windoz.local]
   address = [192.168.137.1]
   port = [8300]
   txt = ["launchport=8273;"]

```

On Mac those commands would be

```
$ dns-sd -B _varafm-modem._tcp
Browsing for _varafm-modem._tcp
DATE: ---Wed 22 Nov 2023---
10:34:17.628  ...STARTING...
Timestamp     A/R    Flags  if Domain               Service Type         Instance Name
10:34:17.770  Add        3   7 local.               _varafm-modem._tcp.  IC705FM
10:34:17.770  Add        2   7 local.               _varafm-modem._tcp.  THD74FM
```
and
```
$dns-sd -L "THD74FM" _varafm-modem._tcp
Lookup THD74FM._varafm-modem._tcp.local
DATE: ---Wed 22 Nov 2023---
10:35:06.750  ...STARTING...
10:35:06.751  THD74FM._varafm-modem._tcp.local. can be reached at t4windoz.local.:8300 (interface 7)
 launchport=8273\;
```

In this example, my host is `t4windoz.local`. I can then connect to `varanny` instance on it using

```
$ telnet t4windoz.local 8273
Trying 10.0.1.44...
Connected to t4windoz.local.
Escape character is '^]'.
list
OK
IC705FM
THD74FM
IC705HF
```

**Comment by ae4ml** [comment]
George, 

I have been playing with this over the past 4 days. 
everything shows up as expected in the avahi browse commands you listed

MyVaraFM works for my vara fm connection. 
MyVaraHF doesn't work atall. I get an immediate timeout on the app on my iphone. 

As for the telnet command. it doesn't work for me using the  nam.local 8372  but it does work using the ip address. 

There is no rig control on the HF side. 
{
  "Port": 8273,
  "Modems" : [
    {
      "Name": "MyVaraFM",
      "Type": "fm",
      "Cmd": "C:\\VARA FM\\VARAFM.exe",
      "Config": "C:\\VARA FM\\VARA_FM.ini",
      "Port": 8300
    },
    {
      "Name": "MyVaraHF",
      "Type": "hf",
      "Cmd": "C:\\VARA\\VARA.exe",
      "Config": "C:\\VARA\\VARA_HF.ini",
      "Port": 8300,
      "CatCtrl": {
      }
    }
  ]
}

**Comment by georges** [comment]
1. Do you have a valid .ini file at `C:\VARA\VARA_HF.ini`. Normally default ini file for VARA HF is `C:\VARA\VARA.ini`
2. Is your VARA HF set for port 8300?

**Comment by ae4ml** [comment]
reply
1. I set it back to use the original C:\VARA\VARA.ini
2. I modified my winlink express and vara to use 8400

I modified the varanny file to use 8400 on HF. 
I continue to get timeouts when I try to use HF. 

VaraFM works on. I did notice that shutdown gracefully always fails

**Comment by ae4ml** [comment]
![IMG_8036](https://github.com/islandmagic/varanny/assets/12587287/0d80cbba-f9a8-49e7-9180-39a4fa8750d2)
![IMG_8037](https://github.com/islandmagic/varanny/assets/12587287/9f1cd469-b74b-495f-a323-17d7f58a6564)

I did notice that there is some communications between the iphone and the windows 10 laptop in vara HF. when I look at Audio under HF settings It brings up the signal link levels and I get a response  in  the varanny screen. see attached
