### ISSUE TITLE
Varanny won't start on Windows 11

### ISSUE THREAD

**Issue by kx8u** [islandmagic/varanny#4]
I have installed both VaraHF and VaraFM. Additionally, I have installed hamlib-w64-4.5.5. I updated the Varanny json as shown below:

**{
  "Port": 8273,
  "Modems" : [
    {
      "Name": "IC705FM",
      "Type": "fm",
      "Cmd": "C:\VARA-FM\VARAFM.exe",
      "Config": "C:\VARA-FM\VARAFM.ic705.ini",
      "Port": 8300
    },
    {
      "Name": "IC705HF",
      "Type": "hf",
      "Cmd": "C:\VARA\VARA.exe",
      "Port": 8400,
      "CatCtrl": {
        "Port": 4532,
        "Dialect": "hamlib",
        "Cmd": "C:\Program Files\hamlib-w64-4.5.5\bin\rigctld.exe",
        "Args": "-m 3055 -r com5"
      }
    }
  ]
}**

I am using an ICOM 705 connected over USB Com5. When I run Varanny I get the following error and have not been able to determine the cause:

**C:\Users\david\Downloads\varanny-windows-amd64>varanny.exe
2023/11/29 15:37:42 Loading configuration from C:\Users\david\Downloads\varanny-windows-amd64\varanny.json
2023/11/29 15:37:42 invalid character 'V' in string escape code**

I have looked through the json and could not find an error. What am I doing wrong?

Thanks.

David
KX8U

**Comment by georges** [comment]
`\` are considered escape characters in the `.json` file. To represent a `\` in a windows like path, it needs to be doubled up, so that `C:\VARA\VARA.exe` should be written `C:\\VARA\\VARA.exe`

Additionally, the model number for the IC705 is 3085, unless you've changed CIV configuration.
