### ISSUE TITLE
Different modem and rigctld servers

### ISSUE THREAD

**Issue by cmh716** [islandmagic/varanny#5]
In RadioMail, when manually creating a connection, it's possible to specify different servers for VARA vs Rigctld.

![image](https://github.com/islandmagic/varanny/assets/3275478/c386de74-5985-4b15-9dcf-105413bc78d6)

In varanny, I know I can do something like this:

C:\\hamlib-w64-4.5\\bin\\rigctld.exe -m 2 -r 192.168.0.3 -vvvv

But I find the performance is poor with delayed PTT. It's unclear to me whether it's a hamlib bug or a SDR-Control bug. Ideally, there would be a way for varanny to tell RadioMail to talk to rigctld on an ip and vara on another ip. 

For understanding: I run MacOS SDR-Control with an internal rigctld server. On parallels, I want to run varanny (and vara fm/hf) and link them to SDR-Control via sound devices. 

Is there a way to do this in varanny? I could probably live with doing manual connections and leave both VARAs running 24x7, but I lose the benefits of varanny such as multiple configs and only loading VARA when it's needed.

**Comment by cmh716** [comment]
Also, one other unrelated thing. Let's say my radio is sitting on DV on a vhf frequency. RadioMail will change the frequency (but not the mode) and it'll return to the previous setting. Would it be possible to also correctly set the mode?

**Comment by cmh716** [comment]
It seems that when connecting using VARA HF, it sets the mode to USB-D correctly, but leaves the mode as that upon return to the original frequency. When using VARA fm, no mode change occurs. This is for manually configured RadioMail connections, not varanny.

**Comment by georges** [comment]
Thanks for sharing your setup and thoughtful question. Two part answer:

1. Multihost: To keep the varanny dns-sd footprint simple, I made a design decision to assume VARA and rigctrl would be sitting on the same host, so the IP broadcasted during dns-sd is meant to represent both. So at present the configuration you're describing is not supported. Part of the rational was to keep the amount of information required in the configuration file to a minimum.

2. Mode change: If rigctrld is setup, RadioMail will attempt to set frequency and mode. Currently it will invoke PKTUSB for hf and PKTFM for fm. I was only able to test this on a IC-705 so it's possible other radio expect a different value? The hamlib documentation was support clear to me. In any situation, RadioMail should restore original frequency and mode as well. It's possible there is a bug somewhere. I'll play some more with it.

**Comment by cmh716** [comment]
This helped me troubleshoot the SDR-Control CAT server.  I can see that it's not responding to some of the commands that Hamlib does, such as PKTFM, whereas the actual rigctld server connected to USB is.  I have filed a bug report with the author.  Assuming he's willing to fix the CAT server, I should be able to use varanny with rigctld in network client mode going forward, so no changes would be needed on your side.  Thanks!
